version: '3.0'

services:

  # mysql 이미지를 이용해서 mysql 라는 이름의 컨테이너 작성
  mysql:
    image: mysql:latest
    # 컨테이너가 의도치 않게 종료 혹은 도커 시작 시 자동시작
    restart: always
    environment:
      # 비밀번호
      MYSQL_ROOT_PASSWORD: 1234
      # timezone
      TZ: Asia/Seoul
      # schema
      MYSQL_DATABASE: product_schema
    ports:
      # 포트번호 [로컬 포트]:3306
      - 3308:3306
    volumes:
      - ./data:/var/lib/mysql

  # Redis
  redis:
    image: redis:latest
    # 컨테이너가 의도치 않게 종료 혹은 도커 시작 시 자동시작
    restart: always
    ports:
      # 포트번호 [로컬 포트]:6379
      - "6380:6379"

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8080"
    depends_on:
      - mysql
      - redis