version: '3.0'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./data:/var/lib/mysql

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8004:8080"
    depends_on:cd
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379